pipeline{
	agent any
	stages{
		stage('Hello') {
		steps{
			sh '''
				echo "Hello this is from groovy"
			'''
			}
		}
		stage('Middle') {
		steps{
		sh '''
			echo "This is my Middle stage"
			'''
			}
		}
        stage('Final') {
		steps{
		sh '''
			echo "This is my Final stage"
			'''
			}
		}
        stage('Last') {
		steps{
		sh '''
			echo "This is my Very last stage"
			'''
			}
		}
       
	}
}