pipeline {
    agent {
        
        label 'prod'
    }

    stages{
        stage('host'){
            steps{
                sh 'hostname'
            }
        }        
        stage('Ip adress'){
            steps{
                sh 'hostname -I'
            }
        }
        stage('Disk-utilisation'){
            steps{
                sh 'df -kh '
            }
        }
        stage('memory'){
            steps{
                sh 'free -h'
            }
        }
        stage('cpu-utilsaton'){
            steps{
                sh 'top -bn1 | head -20'
            }
        }         
    }
}