pipeline {
    agent any
    parameters {
        string(name:'ENV', defaultValue:'Prod', Description:'Testing')
    }

    stages{
        stage('build-stage'){
            sh '''
                echo "This is jenkin file"
                echo "Testing parameters"
                echo "Hope it works"    
            '''
        }
    }
}